---
ansible_python_interpreter: /usr/bin/python3
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe
  joe: joe@home.joe.nyland.io
postfix_relay_host:
  host: smtp.home.joe.nyland.io
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
subnets:
  cloud:
    ipv6:
      cidr: fdff:205:2005::20/123
    ipv4:
      cidr: 172.16.255.32/27
  vpn:
    ipv6:
      cidr: fdff:205:2005::/123
    ipv4:
      cidr: 172.16.255.0/27
  lan:
    ipv6:
      cidr: fdaa:205:2005:10::/64
    ipv4:
      cidr: 10.10.0.0/16
timezone: Europe/London
