---
ansible_python_interpreter: /usr/bin/python3
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
postfix_aliases:
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: joe@home.joe.nyland.io
  hostmaster: root
  security: root
  root: joe@home.joe.nyland.io
postfix_relay_host:
  host: smtp.home.joe.nyland.io
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
timezone: Europe/London
