---
acme_server_url: https://ca.home.joe.nyland.io/acme/acme/directory
ansible_python_interpreter: /usr/bin/python3
certbot_admin_email: joe@home.joe.nyland.io
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
postfix_aliases:
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: joe@home.joe.nyland.io
  hostmaster: root
  security: root
  root: joe@home.joe.nyland.io
postfix_relay_host:
  host: smtp.home.joe.nyland.io
timezone: Europe/London
