---
ansible_python_interpreter: /usr/bin/python3
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe
  joe: joenyland@me.com
  syncoid: joe
postfix_host_name: "{{ ansible_fqdn }}"
postfix_mail_name: nyland.io
postfix_relay_host:
  host: smtp.home.joe.nyland.io
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
subnets:
  cloud:
    ipv6:
      cidr: fc00:f00d:cafe:8:1::/80
    ipv4:
      cidr: 10.8.1.0/24
  vpn:
    ipv6:
      cidr: fc00:f00d:cafe:8::/80
    ipv4:
      cidr: 10.8.0.0/24
  lan:
    ipv6:
      cidr: fc00:f00d:cafe:10::/64
    ipv4:
      cidr: 10.10.0.0/16
