---
acme_server_url: https://ca.home.joe.nyland.io:9000/acme/acme/directory
ansible_python_interpreter: /usr/bin/python3
certbot_admin_email: joe@home.joe.nyland.io
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
postfix_aliases:
  admin: root
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: root
  hostmaster: root
  security: root
  root: joe@home.joe.nyland.io
postfix_relay_host:
  host: smtp.home.joe.nyland.io
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
timezone: Europe/London
