---
acme_server_url: https://ca.home.joe.nyland.io:9000/acme/acme/directory
ansible_python_interpreter: /usr/bin/python3
certbot_admin_email: admin@home.joe.nyland.io
certbot_create_extra_args: "--server {{ acme_server_url }}"
docker_users:
  - joe
homeshick_dotfiles_repos:
  dotfiles: git@github.com:JoeNyland/dotfiles.git
journalctl_users:
  - joe
postfix_aliases:
  admin: joe
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: admin
  hostmaster: admin
  security: admin
  joe: joe@home.joe.nyland.io
  root: admin
  syncoid: admin
  webmaster: admin
postfix_relay_host:
  host: smtp.home.joe.nyland.io
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
timezone: Europe/London
