---
certbot_certs:
  - domains:
      - "{{ ansible_hostname }}"
      - "{{ ansible_fqdn }}"
      - imap.home.joe.nyland.io
      - smtp.home.joe.nyland.io
certbot_deploy_hooks:
  - name: restart-postfix
    content: systemctl restart postfix.service
  - name: restart-dovecot
    content: systemctl restart dovecot.service
dovecot_mailbox_location: maildir:~/.maildir
dovecot_auth_username_format: "%Ln"
dovecot_ssl_certificate: "/etc/letsencrypt/live/{{ ansible_hostname }}/fullchain.pem"
dovecot_ssl_key: "/etc/letsencrypt/live/{{ ansible_hostname }}/privkey.pem"
postfix_destinations:
  - localhost
  - "{{ ansible_hostname }}"
  - "{{ ansible_fqdn }}"
  - "{{ ansible_domain }}"
postfix_inet_interfaces: all
postfix_mailbox_transport: lmtp:unix:private/dovecot-lmtp
postfix_networks:
  - "127.0.0.0/8"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
postfix_smtpd_tls_cert_file: "/etc/letsencrypt/live/{{ ansible_hostname }}/fullchain.pem"
postfix_smtpd_tls_key_file: "/etc/letsencrypt/live/{{ ansible_hostname }}/privkey.pem"
users:
  joe:
    shell: /usr/sbin/nologin
