---
certbot_certs:
  - domains:
      - "mail.{{ ansible_domain }}"
      - "imap.{{ ansible_domain }}"
      - "smtp.{{ ansible_domain }}"
certbot_deploy_hooks:
  - name: restart-postfix
    content: systemctl restart postfix.service
  - name: restart-dovecot
    content: systemctl restart dovecot.service
dovecot_mailbox_location: maildir:~/.maildir
dovecot_auth_username_format: "%Ln"
dovecot_ssl_certificate: "/etc/letsencrypt/live/mail.{{ ansible_domain }}/fullchain.pem"
dovecot_ssl_key: "/etc/letsencrypt/live/mail.{{ ansible_domain }}/privkey.pem"
postfix_destinations:
  - localhost
  - "{{ ansible_hostname }}"
  - "{{ ansible_fqdn }}"
  - "{{ ansible_domain }}"
  - "{{ ansible_domain.split('.')[0] }}"
postfix_inet_interfaces: all
postfix_mailbox_transport: lmtp:unix:private/dovecot-lmtp
postfix_networks:
  - "127.0.0.0/8"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
postfix_smtpd_tls_cert_file: "/etc/letsencrypt/live/mail.{{ ansible_domain }}/fullchain.pem"
postfix_smtpd_tls_key_file: "/etc/letsencrypt/live/mail.{{ ansible_domain }}/privkey.pem"
