---
ansible_become_method: su
ansible_ssh_user: root
certbot_certs:
  - domains:
      - "{{ ansible_hostname }}"
      - "{{ ansible_fqdn }}"
certbot_deploy_hooks:
  - name: restart-pveproxy
    content: |
      cp /etc/letsencrypt/live/pve/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
      cp /etc/letsencrypt/live/pve/privkey.pem /etc/pve/local/pveproxy-ssl.key
      systemctl restart pveproxy
root_user_enabled: true
ssh_authorized_keys:
  - user: root
    key: https://github.com/joenyland.keys
ssh_permit_root_login: true
