---
ansible_become_method: su
ansible_ssh_user: root
certbot_certs:
  - domains:
      - "{{ ansible_hostname | lower }}"
      - "{{ ansible_fqdn | lower }}"
certbot_deploy_hooks:
  - name: restart-pveproxy
    content: |
      cp /etc/letsencrypt/live/{{ ansible_hostname | lower }}/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
      cp /etc/letsencrypt/live/{{ ansible_hostname | lower }}/privkey.pem /etc/pve/local/pveproxy-ssl.key
      systemctl restart pveproxy
  - name: restart-portainer
    content: |
      cp /etc/letsencrypt/live/{{ ansible_hostname | lower }}/fullchain.pem /containers/portainer/certs/cert.pem
      cp /etc/letsencrypt/live/{{ ansible_hostname | lower }}/privkey.pem /containers/portainer/certs/key.pem
      docker restart portainer
docker_daemon_config:
  storage-driver: zfs
root_user_enabled: true
ssh_authorized_keys:
  - user: root
    key: https://github.com/joenyland.keys
ssh_permit_root_login: true
sudo_users: []
