---
- name: Configure journald
  become: true
  tags:
    - journal
    - journald
    - logging
  block:
    - name: Manage config file
      template:
        src: journald.conf.j2
        dest: /etc/systemd/journald.conf
        mode: '0644'
        owner: root
        group: root
      notify: Restart systemd-journald
