---
- name: Update aliases
  command: newaliases

- name: Update SASL hash
  command: postmap /etc/postfix/sasl/passwd

- name: Reload Postfix
  service:
    name: postfix
    state: reloaded
  when: postfix_service.enabled
