---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: server
    image: docker.io/debian:bullseye
    pre_build_image: false
    systemd: always
    privileged: true
provisioner:
  name: ansible
  options:
    diff: true
