---
- name: Prepare
  hosts: all
  become: true

  tasks:
    # These packages are installed by default on a normal system, but are not installed in a Debian Docker image
    - name: Install base packages
      apt:
        name:
          - iptables
          - iproute2
          - procps
          - ssh

    # These packages are installed by default on a normal system, but are not installed in a Debian Docker image
    - name: Start and enable SSH
      service:
        name: ssh
        state: started
        enabled: true
