---
- name: Create system user
  user:
    name: qbittorrent
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Add user to groups
  user:
    name: qbittorrent
    groups: "{{ qbittorrent_groups }}"
    append: true

- name: Install
  apt:
    name: qbittorrent-nox

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/qbittorrent.service
    src: qbittorrent.service
    mode: '644'
  notify: reload_systemd

- name: Create config directory
  file:
    name: /var/lib/qbittorrent/.config/qBittorrent/
    state: directory
    owner: qbittorrent
    group: qbittorrent
    mode: '755'

- name: Configure
  copy:
    dest: /var/lib/qbittorrent/.config/qBittorrent/qBittorrent.conf
    src: qbittorrent.conf
    owner: qbittorrent
    group: qbittorrent
    force: false
    mode: '644'
  notify: restart_qbittorrent

- name: Configure service
  service:
    name: qbittorrent
    state: started
    enabled: true
  register: qbittorrent_service
