---
roles:
  - src: joenyland.abcde
  - src: joenyland.debian_backports
  - src: joenyland.plexmediaserver
  - src: joenyland.qbittorrent
  - src: joenyland.updates
  - src: joenyland.utils
  - src: joenyland.vim
  - src: joenyland.wireguard
collections:
  - community.general
