---
roles:
  - src: joenyland.abcde
  - src: joenyland.docker
  - src: joenyland.dovecot
  - src: joenyland.dropbear_initramfs
  - src: joenyland.get_iplayer
  - src: joenyland.homeshick
  - src: joenyland.nfs_server
  - src: joenyland.off_site_backup
  - src: joenyland.plexmediaserver
  - src: joenyland.postfix
  - src: joenyland.qbittorrent
  - src: joenyland.root_user
  - src: joenyland.samba
  - src: joenyland.sanoid
  - src: joenyland.ssh
  - src: joenyland.sudo
  - src: joenyland.updates
  - src: joenyland.utils
  - src: joenyland.vim
  - src: joenyland.wireguard
  - src: joenyland.zfs
  - src: nginxinc.nginx
  - src: nginxinc.nginx_config
collections:
  - community.general
