---
collections:
  - community.general
roles:
  - name: joenyland.dovecot
    src: https://github.com/JoeNyland/ansible-dovecot-role
  - name: joenyland.homeshick
    src: https://github.com/JoeNyland/ansible-homeshick-role
  - name: joenyland.hostname
    src: https://github.com/JoeNyland/ansible-hostname-role
  - name: joenyland.journalctl
    src: https://github.com/JoeNyland/ansible-journalctl-role
  - name: joenyland.off_site_backup
    src: https://github.com/JoeNyland/ansible-off-site-backup-role
  - name: joenyland.postfix
    src: https://github.com/JoeNyland/ansible-postfix-role
  - name: joenyland.root_user
    src: https://github.com/JoeNyland/ansible-root-user-role
  - name: joenyland.sanoid
    src: https://github.com/JoeNyland/ansible-sanoid-role
  - name: joenyland.ssh
    src: https://github.com/JoeNyland/ansible-ssh-role
  - name: joenyland.step_cli
    src: https://github.com/JoeNyland/ansible-step-cli-role
  - name: joenyland.sudo
    src: https://github.com/JoeNyland/ansible-sudo-role
  - name: joenyland.timezone
    src: https://github.com/JoeNyland/ansible-timezone-role
  - name: joenyland.updates
    src: https://github.com/JoeNyland/ansible-updates-role
  - name: joenyland.users
    src: https://github.com/JoeNyland/ansible-users-role
  - name: joenyland.vim
    src: https://github.com/JoeNyland/ansible-vim-role
  - name: joenyland.wireguard
    src: https://github.com/JoeNyland/ansible-wireguard-role
  - name: joenyland.zfs
    src: https://github.com/JoeNyland/ansible-zfs-role
  - name: geerlingguy.certbot
    src: https://github.com/geerlingguy/ansible-role-certbot
    version: 5.1.1
  - src: nginxinc.nginx
  - src: nginxinc.nginx_config
