---
- name: Setup hostnames and domains
  hosts: all
  become: true
  tags:
    - hostname
    - domain
    - notest # Can't set hostname in tests
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
    - name: Configure hostname and FQDN in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: ^127\.0\.1\.1
        line: "127.0.1.1\t{{ hostname }}.{{ domain }} {{ hostname }}"
        mode: '0644'

- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.updates
    - joenyland.sudo
    - joenyland.ssh
    - joenyland.root_user
    - joenyland.vim
    - joenyland.postfix
    - joenyland.homeshick
  tasks:
    - name: Set timezone
      timezone:
        name: "{{ timezone }}"
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx
        update_cache: true

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.abcde
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.dropbear_initramfs
    - joenyland.samba
    - joenyland.nfs_server
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.get_iplayer

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
