---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - disable_quiet_boot
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.sudo
    - joenyland.users
    - joenyland.timezone
    - joenyland.updates
    - joenyland.homeshick
    - joenyland.step_cli
    - joenyland.vim
    - root_ca
  tasks:
    - name: Install utils
      apt:
        name:
          - bash-completion
          - bsd-mailx
          - fio
          - git
          - gnupg
          - htop
          - iperf3
          - ncdu
          - rsync
          - smartmontools
          - tmux
          - tree
          - vim

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.nfs_server
    - certbot
    - dropbear_initramfs
    - netatalk
    - zfs_load_key

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.off_site_backup

- name: Setup storage servers
  hosts:
    - backup-pi
    - server
  roles:
    - joenyland.zfs
    - joenyland.sanoid

- name: Setup mail servers
  hosts: mail
  roles:
    - certbot
    - joenyland.dovecot
    - joenyland.postfix

- name: Setup Docker machines
  hosts: docker_machine
  roles:
    - certbot
    - joenyland.docker
    - portainer

- name: Setup cloud hosts
  hosts: cloud
  roles:
    - joenyland.wireguard
    - github_ipv6_proxy

- name: Setup web server hosts
  hosts: vps
  roles:
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
