---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.homeshick
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.step_cli
    - joenyland.sudo
    - joenyland.timezone
    - joenyland.updates
    - joenyland.vim
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx

- name: Setup Server
  hosts: server
  become: true
  roles:
    - geerlingguy.certbot
    - joenyland.abcde
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.dropbear_initramfs
    - joenyland.samba
    - joenyland.nfs_server
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.get_iplayer
  tasks:
    - name: Create certbot deploy hook directory
      file:
        path: /etc/letsencrypt/renewal-hooks/deploy
        state: directory
        mode: '0755'
    - name: Create certbot deploy script
      copy:
        dest: /etc/letsencrypt/renewal-hooks/deploy/restart-postfix.sh
        mode: '0777'
        content: systemctl restart postfix

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
  tasks:
    - name: Create user
      user:
        name: joe
        shell: /usr/sbin/nologin
        password_lock: true
      tags: user

- name: Setup PVE
  hosts: pve
  become: true
  roles:
    - geerlingguy.certbot
  tasks:
    - name: Create certbot deploy hook directory
      file:
        path: /etc/letsencrypt/renewal-hooks/deploy
        state: directory
        mode: '0755'
    - name: Create certbot deploy script
      copy:
        dest: /etc/letsencrypt/renewal-hooks/deploy/restart-pveproxy.sh
        mode: '0777'
        content: |
          cp /etc/letsencrypt/live/pve/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
          cp /etc/letsencrypt/live/pve/privkey.pem /etc/pve/local/pveproxy-ssl.key
          systemctl restart pveproxy
