---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - disable_quiet_boot
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.sudo
    - joenyland.users
    - joenyland.timezone
    - joenyland.updates
    - joenyland.homeshick
    - joenyland.step_cli
    - joenyland.vim
    - root_ca
  tasks:
    - name: Install utils
      apt:
        name:
          - bash-completion
          - bsd-mailx
          - fio
          - git
          - gnupg
          - htop
          - iperf3
          - rsync
          - smartmontools
          - tmux
          - tree
          - vim

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.certbot
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.nfs_server
    - joenyland.sanoid
    - joenyland.zfs
    - dropbear_initramfs
    - portainer
    - zfs_load_key

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - github_ipv6_proxy
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
