---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - updates
    - sudo
    - ssh
    - root_user
    - vim
    - utils
    - debian_backports
    - role: homeshick
      become: false

- name: Setup Server
  hosts: server
  become: true
  roles:
    - postfix
    - plexmediaserver
    - samba
    - qbittorrent
    - abcde
    - nfs_server
    - sanoid
    - zfs
    - dropbear

- name: Setup user for Syncoid
  hosts: backup-pi,server
  become: true
  roles:
    - role: syncoid_user
      syncoid_user_destination_host: backup-pi
      syncoid_user_source_host: server

- name: Setup backup server
  hosts: backup-pi
  become: true
  roles:
    - sanoid
    - postfix
    - wireguard
    - zfs
    - role: off_site_backup
      off_site_backup_tasks:
        - source: syncoid@server:bpool
          destination: off-site/bpool
        - source: syncoid@server:rpool
          destination: off-site/rpool
          send_options:
            # For encrypted datasets, send data exactly as it exists on disk.
            # This allows backups to be taken even if encryption keys are not currently loaded.
            - w
        - source: syncoid@server:tank
          destination: off-site/enc/tank
