---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.updates
    - joenyland.sudo
    - joenyland.ssh
    - joenyland.root_user
    - joenyland.vim
    - joenyland.utils
    - joenyland.postfix
    - joenyland.debian_backports
    - joenyland.homeshick

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.abcde
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.dropbear_initramfs
    - joenyland.samba
    - joenyland.nfs_server
    - joenyland.plexmediaserver
    - joenyland.off_site_backup
    - joenyland.docker
    - role: robertdebock.dovecot
      tags:
        - dovecot
        - email

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.wireguard
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
