---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - disable_quiet_boot
    - joenyland.homeshick
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.step_cli
    - joenyland.sudo
    - joenyland.timezone
    - joenyland.updates
    - joenyland.users
    - joenyland.vim
    - root_ca
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx

- name: Setup physical systems
  hosts: physical
  become: true
  tasks:
    - name: Install utils
      apt:
        name:
          - iperf3
          - fio
          - smartmontools

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup server
  hosts: server
  become: true
  roles:
    - joenyland.certbot
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.nfs_server
    - joenyland.sanoid
    - joenyland.zfs
    - netatalk
    - portainer
    - zfs_load_key
