---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - updates
    - sudo
    - ssh
    - vim
    - utils
    - debian-backports
    - role: homeshick
      become: false

- name: Setup Server
  hosts: server
  become: true
  roles:
    - backup
    - postfix
    - plexmediaserver
    - samba
    - qbittorrent
    - abcde
    - nfs-server
    - sanoid
    - zfs

- name: Setup user for Syncoid
  hosts: backup-pi,server
  become: true
  roles:
    - role: syncoid-user
      syncoid_user_destination_host: backup-pi
      syncoid_user_source_host: server

- name: Setup backup server
  hosts: backup-pi
  become: true
  roles:
    - sanoid
    - postfix
    - wireguard
    - zfs
    - role: off-site-backup
      off_site_backup_source: syncoid@server:tank/ds1
      off_site_backup_destination: off-site/enc/tank/ds1
