---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.updates
    - sudo
    - ssh
    - root_user
    - joenyland.vim
    - joenyland.utils
    - joenyland.debian_backports
    - joenyland.homeshick

- name: Setup Server
  hosts: server
  become: true
  roles:
    - postfix
    - joenyland.abcde
    - joenyland.zfs
    - sanoid
    - joenyland.dropbear_initramfs
    - samba
    - nfs_server
    - joenyland.qbittorrent
    - joenyland.plexmediaserver
    - syncoid_user

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - postfix
    - joenyland.zfs
    - sanoid
    - joenyland.wireguard
    - syncoid_user
    - off_site_backup
