---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - disable_quiet_boot
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.sudo
    - joenyland.users
    - joenyland.timezone
    - joenyland.updates
    - root_ca

- name: Setup systems which aren't LXCs
  hosts: all:!proxmox_all_lxc
  become: true
  roles:
    - joenyland.homeshick
    - joenyland.step_cli
    - joenyland.vim
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx

- name: Setup physical systems
  hosts: physical
  become: true
  tasks:
    - name: Install utils
      apt:
        name:
          - iperf3
          - ncdu
          - rsync
          - fio
          - smartmontools

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.off_site_backup

- name: Setup storage servers
  hosts:
    - backup-pi
    - proxmox_nodes
  roles:
    - joenyland.zfs
    - joenyland.sanoid

- name: Setup mail servers
  hosts: mail
  roles:
    - certbot
    - joenyland.dovecot
    - joenyland.postfix

- name: Setup Docker machines
  hosts: docker_machine
  roles:
    - certbot
    - joenyland.docker
    - portainer

- name: Setup cloud hosts
  hosts: cloud
  roles:
    - joenyland.wireguard
    - github_ipv6_proxy

- name: Setup web server hosts
  hosts: vps
  roles:
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx

- name: Setup PVE nodes
  hosts: proxmox_nodes
  become: true
  roles:
    - joenyland.nfs_server
    - zfs_load_key
    - certbot

- name: Setup Netatalk container
  hosts: netatalk
  become: true
  roles:
    - netatalk
