---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.updates
    - sudo
    - ssh
    - root_user
    - vim
    - joenyland.utils
    - joenyland.debian_backports
    - role: homeshick
      become: false

- name: Setup Server
  hosts: server
  become: true
  roles:
    - postfix
    - abcde
    - zfs
    - sanoid
    - dropbear
    - samba
    - nfs_server
    - qbittorrent
    - joenyland.plexmediaserver
    - syncoid_user

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - postfix
    - zfs
    - sanoid
    - joenyland.wireguard
    - syncoid_user
    - off_site_backup
