---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.homeshick
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.step_cli
    - joenyland.sudo
    - joenyland.timezone
    - joenyland.updates
    - joenyland.users
    - joenyland.vim
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - fio
          - git
          - iperf3
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx
          - smartmontools

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.abcde
    - joenyland.certbot
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.dropbear_initramfs
    - joenyland.samba
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.get_iplayer

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx

- name: Setup PVE
  hosts: pve
  become: true
  roles:
    - joenyland.certbot
    - joenyland.nfs_server
    - joenyland.sanoid
    - joenyland.zfs
