---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - updates
    - sudo
    - ssh
    - vim
    - utils
    - debian-backports
    - role: homeshick
      become: false

- name: Setup Server
  hosts: server
  become: true
  roles:
    - backup
    - postfix
    - plexmediaserver
    - samba
    - qbittorrent
    - abcde
    - nfs-server
    - sanoid
