---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.sudo
    - joenyland.users
    - joenyland.timezone
    - joenyland.updates
    - root_ca

- name: Setup systems which aren't LXCs
  hosts: all:!proxmox_all_lxc
  become: true
  roles:
    - joenyland.homeshick
    - joenyland.step_cli
    - joenyland.vim
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx

- name: Setup physical systems
  hosts: physical
  become: true
  tasks:
    - name: Install utils
      apt:
        name:
          - iperf3
          - fio
          - smartmontools

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx

- name: Setup PVE
  hosts: proxmox_nodes
  become: true
  roles:
    - joenyland.certbot
    - joenyland.nfs_server
    - joenyland.sanoid
    - joenyland.zfs

- name: Setup mail server container
  hosts: mail
  become: true
  roles:
    - joenyland.certbot
    - joenyland.dovecot

- name: Setup file server container
  hosts: netatalk
  become: true
  roles:
    - netatalk

- name: Setup Docker VM
  hosts: docker_vm
  become: true
  roles:
    - joenyland.docker
    - docker_host_storage
    - portainer
