---
- name: Setup all systems
  hosts: all:!unifi
  become: true
  roles:
    - disable_quiet_boot
    - joenyland.homeshick
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.step_cli
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.ssh
    - joenyland.sudo
    - joenyland.timezone
    - joenyland.updates
    - joenyland.users
    - joenyland.vim
    - root_ca
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx
          - iperf3
          - ncdu
          - rsync
          - fio
          - smartmontools

- name: Setup NAS
  hosts: nas
  become: true
  roles:
    - certbot
    - joenyland.dovecot
    - joenyland.postfix
    - dropbear_initramfs
    - joenyland.docker
    - portainer
    - plex
    - samba
    - joenyland.zfs
    - joenyland.sanoid
    - zfs_load_key
  tasks:
    - name: Create media group
      group:
        name: media
        system: true
    - name: Add joe to media group
      user:
        name: joe
        groups: media
        append: true

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.off_site_backup
    - joenyland.zfs
    - joenyland.sanoid

- name: Setup VPS
  hosts: vps
  become: true
  roles:
    - joenyland.wireguard
    - github_ipv6_proxy
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx

- name: Setup UniFi controller
  hosts: unifi
  roles:
    - root_ca
    - joenyland.step_cli
    - certbot
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - tree
          - tmux
          - bash-completion
