---
- name: Setup all systems
  hosts: all
  become: true
  roles:
    - joenyland.homeshick
    - joenyland.hostname
    - joenyland.journalctl
    - joenyland.postfix
    - joenyland.root_user
    - joenyland.sudo
    - joenyland.timezone
    - joenyland.updates
    - joenyland.vim
  tasks:
    - name: Install utils
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
          - bsd-mailx

- name: Setup Server
  hosts: server
  become: true
  roles:
    - joenyland.abcde
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.dropbear_initramfs
    - joenyland.samba
    - joenyland.nfs_server
    - joenyland.docker
    - joenyland.dovecot
    - joenyland.get_iplayer
    - joenyland.step_cli

- name: Setup Backup-Pi
  hosts: backup-pi
  become: true
  roles:
    - joenyland.zfs
    - joenyland.sanoid
    - joenyland.off_site_backup
  tasks:
    - name: Install Step CLI
      apt:
        deb: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_arm64.deb
      tags:
        - step
        - notest # Can't install arm64 packages in tests

- name: Setup VPS
  hosts: vps
  roles:
    - joenyland.docker
    - joenyland.wireguard
    - role: nginxinc.nginx
      tags: nginx
    - role: nginxinc.nginx_config
      tags: nginx
  tasks:
    - name: Create user
      user:
        name: joe
        shell: /usr/sbin/nologin
        password_lock: true
      tags: user
