---
- name: Add hosts file entries
  blockinfile:
    marker: "# {mark} IPv6 access to github.com"
    path: /etc/hosts
    block: |
      2a01:4f8:c010:d56::2 github.com
      2a01:4f8:c010:d56::3 api.github.com
      2a01:4f8:c010:d56::4 codeload.github.com
      2a01:4f8:c010:d56::5 objects.githubusercontent.com
      2a01:4f8:c010:d56::6 ghcr.io
      2a01:4f8:c010:d56::7 pkg.github.com npm.pkg.github.com maven.pkg.github.com nuget.pkg.github.com rubygems.pkg.github.com
    prepend_newline: true
  tags: github
