---
- name: Install root CA
  tags:
    - ca
    - root_ca
    - ssl
  become: true
  block:
    - name: Make sure the folder exists
      file:
        path: /usr/local/share/ca-certificates
        state: directory
        mode: '0755'

    - name: Install the certificate
      get_url:
        url: https://nyland.io/~joe/ca.crt
        dest: /usr/local/share/ca-certificates/joe_nyland_root_ca.crt
        mode: '0644'
      notify: Update CA trust
