---
- name: Setup Netatalk
  become: true
  tags: netatalk
  block:
    - name: Install netatalk from unstable (sid) repo on Debian 12 (bookworm)
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_major_version'] == '12'
      block:
        - name: Add unstable repository
          apt_repository:
            repo: deb http://deb.debian.org/debian unstable main
            filename: unstable
            state: present

        - name: Configure apt package preferences
          file:
            dest: /etc/apt/preferences.d
            state: directory
            mode: '0755'

        - name: Configure apt package preferences
          copy:
            dest: /etc/apt/preferences.d/unstable
            mode: '0644'
            content: |
              Package: *
              Pin: release a=unstable
              Pin-Priority: 100
          notify: Update package repo caches

        - name: Update package repo caches
          meta: flush_handlers

        - name: Install netatalk from unstable (sid) repo
          apt:
            name:
              - netatalk
              - libgcrypt20 # The version of netatalk in sid depends on a newer version of this lib
            state: latest # noqa: package-latest
            default_release: unstable

    - name: Install netatalk
      apt:
        name: netatalk
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_major_version'] != '12'

    - name: Set server name
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: Global
        option: hostname
        value: "{{ netatalk_server_name }}"
        mode: '0644'
      notify: Restart netatalk

    - name: Set server type
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: Global
        option: mimic model
        value: "{{ netatalk_server_model }}"
        mode: '0644'
      notify: Restart netatalk

    - name: Enable Spotlight
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: Global
        option: spotlight
        value: "{{ netatalk_spotlight_enabled | ternary('yes', 'no') }}"
        mode: '0644'
      notify: Restart netatalk

    - name: Configure Homes
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: Homes
        option: basedir regex
        value: /home
        mode: '0644'
      notify: Reload netatalk

    - name: Enable Time Capsule
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: "{{ netatalk_time_capsule_share_name }}"
        option: time machine
        value: 'yes'
        mode: '0644'
      notify: Reload netatalk

    - name: Configure Time Capsule share path
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: "{{ netatalk_time_capsule_share_name }}"
        option: path
        value: "{{ netatalk_time_capsule_path }}"
        mode: '0644'
      notify: Reload netatalk

    - name: Configure share(s)
      community.general.ini_file:
        path: /etc/netatalk/afp.conf
        section: "{{ item.key }}"
        option: path
        value: "{{ item.value }}"
        mode: '0644'
      with_dict: "{{ netatalk_shares }}"
      notify: Reload netatalk
