---
- name: Disable password-based login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^( *)?PasswordAuthentication
    line: PasswordAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd

- name: Add authorised SSH keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    exclusive: true  # Only allow keys specified here
  with_items: "{{ ssh_authorized_keys }}"
