---
- name: Mount /tank
  become: true
  tags:
    - tank
    - mount
  block:
    - name: Install NFS client
      apt:
        name: nfs-client

    - name: Mount
      mount:
        path: /tank
        src: server:/tank
        fstype: nfs4
        state: mounted
