---
- name: Disable root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^( *)?PermitRootLogin
    line: PermitRootLogin no
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd

- name: Disable root password
  user:
    name: root
    password_lock: true
