---
- name: Converge
  hosts: all
  gather_facts: false

- name: Import playbook
  import_playbook: ../../site.yml
  vars:
    certbot_certs: []
    # We override dotfiles URL here so that in CI we can install dotfiles without SSH keys.
    homeshick_dotfiles_repos:
      dotfiles: https://github.com/JoeNyland/dotfiles.git
    docker_daemon_config: {} # Various config not available in CI, so reset to empty hash.
    # We can't run ZFS in CI, so we can't create datasets, either
    zfs_datasets: {}
    # Override the Wireguard interface configuration, omitting the DNS config as this would break DNS in CI.
    wireguard_interfaces:
      wg0:
        address: 10.8.0.104/24
        post_up:
          - wg set %i private-key /etc/wireguard/private.key
        peers: []
    # Override these to match the container names in CI, rather than FQDNs (which would not resolve)
    off_site_backup_destination_host: backup-pi
    off_site_backup_source_host: server
