---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: "geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      # The below are stubs for ZFS provided volumes
      - /tank
      - /home
    cgroupns_mode: host
    privileged: true
  - name: backup-pi
    image: "geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
  - name: vps
    image: "geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
