---
- name: Prepare
  hosts: all
  become: true
  tasks:
    # SSH is installed and running by default on a normal Debian system, but not in a Docker image
    - name: Install SSH
      apt:
        name: ssh
        update_cache: true
    - name: Start and enable SSH
      service:
        name: ssh
        state: started
        enabled: true

- name: Create resources skipped by plexmediaserver package
  hosts: server
  become: true
  tasks:
    # The plexmediaserver package detects if it's being installed in a Docker container and
    # opts not to install the systemd service file or user. The following works around this.
    - name: Install plexmediaserver service file
      copy:
        src: plexmediaserver.service
        dest: /lib/systemd/system/plexmediaserver.service
        mode: '0644'
    - name: Create system user
      user:
        name: plex
        system: true
        shell: /usr/sbin/nologin
        create_home: false
        home: /var/lib/plexmediaserver
    - name: Create system user home
      file:
        name: /var/lib/plexmediaserver
        state: directory
        mode: '0755'
        owner: plex
        group: plex
