---
- name: Prepare
  hosts: all
  become: true
  tasks:
    # SSH is installed and running by default on a normal Debian system, but not in a Docker image
    - name: Install SSH
      apt:
        name: ssh
        update_cache: true
    - name: Start and enable SSH
      service:
        name: ssh
        state: started
        enabled: true
    # User needs to exist
    - name: Create user
      user:
        name: syncoid
        system: true
        password_lock: true