---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Install WireGuard
      apt:
        name: wireguard
      notify: remove_wireguard

    - name: Generate a WireGuard private key  # noqa risky-shell-pipe
      shell: |
        cd /etc/wireguard
        umask 077
        wg genkey | tee private.key | wg pubkey > public.key
      args:
        creates: /etc/wireguard/private.key

  handlers:
    - name: remove_wireguard
      apt:
        name: wireguard
        state: absent
        autoremove: true
