---
- name: Create container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/portainer:/data
