---
- name: Create container
  docker_container:
    name: portainer_agent
    image: portainer/agent
    network_mode: host
    ports:
      - 9001:9001
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
