---
debian_backports_additional_components:
  - contrib
off_site_backup_tasks:
  - source: syncoid@server.home.joe.nyland.io:bpool
    destination: off-site/bpool
    hour: 1
    minute: 0
  - source: syncoid@server.home.joe.nyland.io:rpool
    destination: off-site/rpool
    send_options:
      # For encrypted datasets, send data exactly as it exists on disk.
      # This allows backups to be taken even if encryption keys are not currently loaded.
      - w
    hour: 1
    minute: 30
off_site_backup_destination_host: backup-pi
off_site_backup_source_host: server.home.joe.nyland.io
wireguard_interfaces:
  wg0:
    address: 10.8.1.2/24, fc00:f00d:cafe:8:1::2/80
    mtu: 1400
    post_up:
      - wg set %i private-key /etc/wireguard/private.key
    dns:
      - fc00:f00d:cafe:8:1::1
      - 10.8.1.1
      - cloud.joe.nyland.io
    peers:
      - name: Router
        public_key: P3lmTwJlnV/K5CLPkK77C5qOWapCimop5c8eox3FSFg=
        allowed_ips: 10.8.0.0/24, 10.8.1.0/24, 10.10.0.0/16, fc00:f00d:cafe:8::/80, fc00:f00d:cafe:8:1::/80, fc00:f00d:cafe:10::/64
        endpoint: home.joe.nyland.io:51821
        keep_alive: 25
      - name: VPS
        public_key: TWDiuTOSz35uQ9KyGIJ9uUS1uZDdHWy8dghNc3FUvGM=
        allowed_ips: 10.8.1.3/32, fc00:f00d:cafe:8:1::3/128
        endpoint: vps.cloud.joe.nyland.io:51821
        keep_alive: 25
sanoid_templates:
  bpool:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  rpool:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
sanoid_policies:
  off-site/bpool:
    use_template: bpool
    recursive: 'yes'
  off-site/rpool:
    use_template: rpool
    recursive: 'yes'
zfs_datasets:
  off-site:
    mountpoint: 'none'
    readonly: 'on'
  off-site/bpool:
    compression: lz4
  off-site/rpool:
    compression: lz4
