---
hostname: Backup-Pi
domain: remote.joe.nyland.io
off_site_backup_tasks:
  - name: Server -> Backup-Pi
    hour: 0
    minute: 30
    tasks:
      - source: syncoid@server:bpool
        destination: off-site/bpool
      - source: syncoid@server:rpool
        destination: off-site/rpool
        send_options:
          # For encrypted datasets, send data exactly as it exists on disk.
          # This allows backups to be taken even if encryption keys are not currently loaded.
          - w
      - source: syncoid@server:tank
        destination: off-site/tank
        send_options:
          # For encrypted datasets, send data exactly as it exists on disk.
          # This allows backups to be taken even if encryption keys are not currently loaded.
          - w
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe
  joe: joe@home.joe.nyland.io
  syncoid: joe
sanoid_templates:
  default:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  off-site/bpool:
    use_template: default
    recursive: 'yes'
  off-site/rpool:
    use_template: default
    recursive: 'yes'
  off-site/tank:
    use_template: default
    recursive: 'yes'
zfs_datasets:
  off-site:
    mountpoint: 'none'
    readonly: 'on'
  off-site/bpool:
    compression: lz4
  off-site/rpool:
    compression: lz4
  off-site/tank:
    compression: lz4
