---
hostname: Backup-Pi
off_site_backup_tasks:
  - name: NAS -> Backup-Pi
    hour: '1'
    minute: '00'
    tasks:
      - source: syncoid@nas:rpool
        destination: off-site/nas/rpool
        send_options:
          # For encrypted datasets, send data exactly as it exists on disk.
          # This allows backups to be taken even if encryption keys are not currently loaded.
          - w
      - source: syncoid@nas:tank
        destination: off-site/tank
        send_options:
          # For encrypted datasets, send data exactly as it exists on disk.
          # This allows backups to be taken even if encryption keys are not currently loaded.
          - w
postfix_aliases:
  admin: root
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: root
  hostmaster: root
  security: root
  root: joe@home.joe.nyland.io
  joe: joe@home.joe.nyland.io
  syncoid: joe
sanoid_templates:
  default:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  off-site/nas:
    use_template: default
    recursive: 'yes'
zfs_datasets:
  off-site:
    mountpoint: 'none'
    readonly: 'on'
  off-site/nas:
    compression: lz4
