---
hostname: Backup-Pi
domain: home.cliff.nyland.io
off_site_backup_tasks:
  - source: syncoid@server.home.joe.nyland.io:bpool
    destination: off-site/bpool
    hour: 1
    minute: 0
  - source: syncoid@server.home.joe.nyland.io:rpool
    destination: off-site/rpool
    send_options:
      # For encrypted datasets, send data exactly as it exists on disk.
      # This allows backups to be taken even if encryption keys are not currently loaded.
      - w
    hour: 1
    minute: 30
  - source: syncoid@server.home.joe.nyland.io:tank
    destination: off-site/tank
    send_options:
      # For encrypted datasets, send data exactly as it exists on disk.
      # This allows backups to be taken even if encryption keys are not currently loaded.
      - w
    hour: 2
    minute: 00
off_site_backup_destination_host: backup-pi
off_site_backup_source_host: server.home.joe.nyland.io
sanoid_templates:
  default:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  off-site/bpool:
    use_template: default
    recursive: 'yes'
  off-site/rpool:
    use_template: default
    recursive: 'yes'
  off-site/tank:
    use_template: default
    recursive: 'yes'
zfs_datasets:
  off-site:
    mountpoint: 'none'
    readonly: 'on'
  off-site/bpool:
    compression: lz4
  off-site/rpool:
    compression: lz4
  off-site/tank:
    compression: lz4
