---
certbot_certs:
  - domains:
      - "{{ ansible_hostname | lower }}"
      - "{{ ansible_fqdn | lower }}"
  - domains:
      - "mail.{{ ansible_domain }}"
      - "imap.{{ ansible_domain }}"
      - "smtp.{{ ansible_domain }}"
certbot_deploy_hooks:
  - name: restart-postfix
    content: systemctl restart postfix.service
  - name: restart-dovecot
    content: systemctl restart dovecot.service
docker_daemon_config:
  storage-driver: zfs
hostname: NAS
plex_user_groups:
  - media # Allow Plex to read from media directories
sabnzbd_user_groups:
  - downloads # Allow SABnzbd to store files in downloads directories
  - media # Allow SABnzbd to store files in media directories
sabnzbd_group_users:
  - joe # Put joe in the sabnzbd group, so that he can manage the files that SABnzbd creates
samba_shares:
  downloads:
    path: /downloads
    valid_users: joe
    read_only: false
  tank:
    path: /tank
    valid_users: joe
    read_only: false
sanoid_templates:
  default:
    autosnap: "yes"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: "no"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  bpool:
    use_template: default
    recursive: "yes"
  rpool:
    use_template: default
    recursive: "yes"
  rpool/downloads:
    use_template: none
    recursive: "yes"
  rpool/var/cache:
    use_template: none
    recursive: "yes"
  rpool/var/lib/docker:
    use_template: none
    recursive: "yes"
  rpool/var/tmp:
    use_template: none
    recursive: "yes"
  tank:
    use_template: default
    recursive: "yes"
servarr_group_users:
  - joe
servarr_user_groups:
  - downloads
  - media
  - sabnzbd
zfs_datasets:
  bpool:
    devices: "off"
    acltype: posix
    xattr: sa
    compression: lz4
    normalization: formD
    relatime: "on"
    canmount: "off"
    mountpoint: /boot
  bpool/BOOT:
    canmount: "off"
    mountpoint: none
  bpool/BOOT/debian:
    mountpoint: /boot
  rpool:
    canmount: 'off'
    compression: lz4
    encryption: aes-256-gcm
    mountpoint: /
  rpool/ROOT:
    mountpoint: 'none'
    canmount: 'off'
  rpool/downloads:
    syncoid:sync: "false"
    compression: "off"
  rpool/usr:
    canmount: "off"
  rpool/var:
    canmount: "off"
  rpool/var/cache:
    syncoid:sync: "false"
  rpool/var/lib:
    canmount: "off"
  rpool/var/lib/docker:
    syncoid:sync: "false"
  rpool/var/tmp:
    syncoid:sync: "false"
  tank/home:
    mountpoint: /home
  tank/home/root:
    mountpoint: /root
