---
certbot_certs:
  - domains:
      - pve
      - pve.home.joe.nyland.io
certbot_deploy_hooks:
  - name: restart-pveproxy
    content: |
      cp /etc/letsencrypt/live/pve/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
      cp /etc/letsencrypt/live/pve/privkey.pem /etc/pve/local/pveproxy-ssl.key
      systemctl restart pveproxy
hostname: pve
domain: home.joe.nyland.io
nfs_exports:
  /containers:
    client_permissions:
      fe80::/10:
        - rw # Allow read/write access
        - crossmnt # Allow mounts inside to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /downloads:
    client_permissions:
      fe80::/10:
        - rw # Allow read/write access
        - crossmnt # Allow mounts inside to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /home:
    client_permissions:
      fe80::/10:
        - rw # Allow read/write access
        - crossmnt # Allow mounts inside to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /tank:
    client_permissions:
      fe80::/10:
        - rw # Allow read/write access
        - crossmnt # Allow mounts inside to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
root_user_enabled: true
sanoid_templates:
  default:
    autosnap: "yes"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: "no"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  danube:
    use_template: default
    recursive: "yes"
  rpool:
    use_template: default
    recursive: "yes"
  rpool/var:
    use_template: none
  rpool/var/cache:
    use_template: none
    recursive: "yes"
  rpool/var/lib:
    use_template: none
  rpool/var/lib/nfs:
    use_template: none
    recursive: "yes"
  rpool/var/tmp:
    use_template: none
    recursive: "yes"
  tank:
    use_template: default
    recursive: "yes"
ssh_authorized_keys:
  - user: root
    key: https://github.com/joenyland.keys
ssh_permit_root_login: true
zfs_datasets:
  danube:
    compression: lz4
  danube/containers:
    mountpoint: /containers
  danube/downloads:
    syncoid:sync: "false"
    compression: "off"
    mountpoint: /downloads
  rpool:
    compression: lz4
  rpool/var:
    canmount: "off"
    mountpoint: /var
  rpool/var/cache:
    syncoid:sync: "false"
  rpool/var/lib:
    canmount: "off"
  rpool/var/lib/nfs:
    syncoid:sync: "false"
  rpool/var/tmp:
    syncoid:sync: "false"
  tank/home:
    mountpoint: /home
