---
certbot_certs:
  - domains:
    - pve
    - pve.home.joe.nyland.io
certbot_deploy_hooks:
  - name: restart-pveproxy
    content: |
      cp /etc/letsencrypt/live/pve/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
      cp /etc/letsencrypt/live/pve/privkey.pem /etc/pve/local/pveproxy-ssl.key
      systemctl restart pveproxy
hostname: pve
domain: home.joe.nyland.io
root_user_enabled: true
ssh_authorized_keys:
  - user: root
    key: https://github.com/joenyland.keys
ssh_permit_root_login: true
