---
docker_users:
  - joe
dovecot_mailbox_location: maildir:~/.maildir
dovecot_auth_username_format: '%Ln'
# Run zfsunlock automatically in initramfs to unlock root pool
dropbear_initramfs_options: '-c /usr/bin/zfsunlock'
dropbear_initramfs_ssh_authorized_keys:
  - https://github.com/joenyland.keys
hostname: Server
hostname_aliases:
  - ca.home.joe.nyland.io
  - homeassistant.home.joe.nyland.io
  - imap.home.joe.nyland.io
  - smtp.home.joe.nyland.io
  - mail.home.joe.nyland.io
domain: home.joe.nyland.io
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe
  syncoid: joe
postfix_destinations:
  - localhost
  - "{{ ansible_hostname }}"
  - "{{ ansible_fqdn }}"
  - "{{ ansible_domain }}"
postfix_inet_interfaces: all
postfix_mailbox_transport: lmtp:unix:private/dovecot-lmtp
postfix_networks:
  - "127.0.0.0/8"
  - "172.17.0.0/16"
  - "10.10.0.0/16" # LAN
  - "172.16.255.0/27"  # VPN
  - "172.16.255.32/27"  # Cloud
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
  - "[fdaa:205:2005:10::]/64" # LAN
  - "[fdff:205:2005::]/123"   # VPN
  - "[fdff:205:2005::20]/123" # Cloud
postfix_smtpd_tls_cert_file: /etc/letsencrypt/live/server/fullchain.pem
postfix_smtpd_tls_key_file: /etc/letsencrypt/live/server/privkey.pem
nfs_exports:
  /home:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /tank:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
samba_shares:
  tank:
    path: /tank
    valid_users: joe
    read_only: false
sanoid_templates:
  default:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  bpool:
    use_template: default
    recursive: 'yes'
  rpool:
    use_template: default
    recursive: 'yes'
  rpool/tank/downloads:
    use_template: none
    recursive: 'yes'
off_site_backup_destination_host: backup-pi
off_site_backup_source_host: server.home.joe.nyland.io
zfs_datasets:
  # Boot
  bpool:
    devices: 'off'
    acltype: posix
    xattr: sa
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /boot
  bpool/BOOT:
    canmount: 'off'
    mountpoint: none
  bpool/BOOT/debian:
    mountpoint: /boot

  # Root
  rpool:
    encryption: aes-256-gcm
    keylocation: prompt
    keyformat: passphrase
    acltype: posix
    xattr: sa
    dnodesize: auto
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /
  rpool/ROOT:
    canmount: 'off'
    mountpoint: 'none'
  rpool/ROOT/debian:
    canmount: noauto
    mountpoint: /
  tank:
  tank/archive:
  tank/archive/apps:
  tank/archive/certificates:
  tank/archive/drivers:
  tank/archive/firmware:
  tank/archive/gaming:
  tank/archive/manuals:
  tank/archive/os:
  tank/archive/vms:
  tank/backups:
  tank/backups/images:
  rpool/containers:
  rpool/containers/home-assistant:
  rpool/containers/lidarr:
  rpool/containers/plex:
  rpool/containers/portainer:
  rpool/containers/prowlarr:
  rpool/containers/qbittorrent:
  rpool/containers/radarr:
  rpool/containers/sabnzbd:
  rpool/containers/sonarr:
  rpool/containers/stash:
  rpool/containers/step-ca:
  rpool/containers/uptime-kuma:
  rpool/containers/whisparr:
  rpool/downloads:
    syncoid:sync: 'false'
    compression: 'off'
  tank/home:
    mountpoint: /home
  tank/home/joe:
  tank/home/root:
    mountpoint: /root
  tank/media/audiobooks:
  tank/media/movies:
  tank/media/music:
  tank/media/photos:
  tank/media/sport:
  tank/media/tv:
  tank/media/videos:
  rpool/var:
    canmount: 'off'
  rpool/var/lib:
    canmount: 'off'
  rpool/var/lib/docker:
  rpool/var/log:
  rpool/var/spool:
