---
certbot_certs:
  - domains:
      - server
      - server.home.joe.nyland.io
      - imap.home.joe.nyland.io
      - smtp.home.joe.nyland.io
      - mail.home.joe.nyland.io
certbot_deploy_hooks:
  - name: restart-postfix
    content: systemctl restart postfix
docker_users:
  - joe
docker_daemon_config:
  storage-driver: zfs
dovecot_mailbox_location: maildir:~/.maildir
dovecot_auth_username_format: "%Ln"
dropbear_initramfs_options: "-c /usr/bin/zfsunlock"
dropbear_initramfs_ssh_authorized_keys:
  - https://github.com/joenyland.keys
hostname: Server
domain: home.joe.nyland.io
journalctl_users:
  - joe
postfix_aliases:
  abuse: postmaster
  mailer-daemon: postmaster
  nobody: postmaster
  postmaster: joe@home.joe.nyland.io
  hostmaster: root
  security: root
  root: joe@home.joe.nyland.io
  joe: joe@home.joe.nyland.io
postfix_destinations:
  - localhost
  - "{{ ansible_hostname }}"
  - "{{ ansible_fqdn }}"
  - "{{ ansible_domain }}"
postfix_inet_interfaces: all
postfix_mailbox_transport: lmtp:unix:private/dovecot-lmtp
postfix_networks:
  - "127.0.0.0/8"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
postfix_smtpd_tls_cert_file: /etc/letsencrypt/live/server/fullchain.pem
postfix_smtpd_tls_key_file: /etc/letsencrypt/live/server/privkey.pem
nfs_exports:
  /containers:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /downloads:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /home:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /tank:
    client_permissions:
      fdaa:205:2005:10::/64:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
samba_shares:
  containers:
    path: /containers
    valid_users: joe
    read_only: false
  downloads:
    path: /downloads
    valid_users: joe
    read_only: false
  tank:
    path: /tank
    valid_users: joe
    read_only: false
sanoid_templates:
  default:
    autosnap: "yes"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    yearly: 0
  none:
    autosnap: "no"
    autoprune: "yes"
    frequently: 0
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  bpool:
    use_template: default
    recursive: "yes"
  rpool:
    use_template: default
    recursive: "yes"
  rpool/downloads:
    use_template: none
    recursive: "yes"
  rpool/var/cache:
    use_template: none
    recursive: "yes"
  rpool/var/lib/docker:
    use_template: none
    recursive: "yes"
  rpool/var/lib/nfs:
    use_template: none
    recursive: "yes"
  rpool/var/tmp:
    use_template: none
    recursive: "yes"
  tank:
    use_template: default
    recursive: "yes"
ssh_authorized_keys:
  - user: joe
    key: https://github.com/joenyland.keys
sudo_users:
  - joe
users:
  joe:
zfs_datasets:
  # Boot
  bpool:
    devices: "off"
    acltype: posix
    xattr: sa
    compression: lz4
    normalization: formD
    relatime: "on"
    canmount: "off"
    mountpoint: /boot
  bpool/BOOT:
    canmount: "off"
    mountpoint: none
  bpool/BOOT/debian:
    mountpoint: /boot

  # Root
  rpool:
    encryption: aes-256-gcm
    keylocation: prompt
    keyformat: passphrase
    acltype: posix
    xattr: sa
    dnodesize: auto
    compression: lz4
    normalization: formD
    relatime: "on"
    canmount: "off"
    mountpoint: /
  rpool/ROOT:
    canmount: "off"
    mountpoint: "none"
  rpool/ROOT/debian:
    canmount: noauto
    mountpoint: /
  rpool/downloads:
    syncoid:sync: "false"
    compression: "off"
  rpool/usr:
    canmount: "off"
  rpool/var:
    canmount: "off"
  rpool/var/cache:
    syncoid:sync: "false"
  rpool/var/lib:
    canmount: "off"
  rpool/var/lib/docker:
    syncoid:sync: "false"
  rpool/var/lib/nfs:
    syncoid:sync: "false"
  rpool/var/tmp:
    syncoid:sync: "false"
  tank/home:
    mountpoint: /home
  tank/home/root:
    mountpoint: /root
