---
debian_backports_additional_components:
  - contrib
dropbear_ssh_authorized_keys:
  - https://github.com/joenyland.keys
postfix_inet_interfaces: all
postfix_networks:
  - "127.0.0.0/8"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
  - "{{ subnets.vpn.ipv4.cidr }}"
  - "{{ subnets.lan.ipv4.cidr }}"
postfix_relay_host:
  host: smtp.postmarkapp.com
  port: 587
  sasl_auth_enabled: true
qbittorrent_users:
  - joe
nfs_exports:
  /home:
    client_permissions:
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /tank:
    client_permissions:
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
sanoid_templates:
  bpool:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  rpool:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  tank:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'no'
    frequently: 0
    hourly: 0
    daily: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  bpool:
    use_template: bpool
    recursive: 'yes'
  rpool:
    use_template: rpool
    recursive: 'yes'
  tank:
    use_template: tank
    recursive: 'yes'
  tank/ds1/downloads:
    use_template: none
    recursive: 'yes'
zfs_datasets:
  # Boot
  bpool:
    devices: 'off'
    acltype: posix
    xattr: sa
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /boot
  bpool/BOOT:
    canmount: 'off'
    mountpoint: none
  bpool/BOOT/debian:
    mountpoint: /boot

  # Root
  rpool:
    encryption: aes-256-gcm
    keylocation: prompt
    keyformat: passphrase
    acltype: posix
    xattr: sa
    dnodesize: auto
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /
  rpool/ROOT:
    canmount: 'off'
    mountpoint: 'none'
  rpool/ROOT/debian:
    canmount: noauto
    mountpoint: /
  rpool/srv:
  rpool/usr:
    canmount: 'off'
  rpool/usr/local:
  rpool/var:
    canmount: 'off'
  rpool/var/lib:
    canmount: 'off'
  rpool/var/log:
  rpool/var/mail:
  rpool/var/spool:

  # Tank
  tank:
    mountpoint: 'none'
  tank/ds1:
    compression: 'on'
    mountpoint: /tank
  tank/ds1/archive/apps:
  tank/ds1/archive/certificates:
  tank/ds1/archive/drivers:
  tank/ds1/archive/firmware:
  tank/ds1/archive/gaming:
  tank/ds1/archive/manuals:
  tank/ds1/archive/os:
  tank/ds1/archive/vm/templates:
  tank/ds1/backups/files:
  tank/ds1/backups/images:
  tank/ds1/downloads:
    syncoid:sync: 'false'
  tank/ds1/git:
  tank/ds1/home:
    mountpoint: /home
  tank/ds1/home/joe:
    encryption: aes-256-gcm
    keyformat: raw
    keylocation: file:///etc/zfs/keys/tank.key
  tank/ds1/home/root:
    mountpoint: /root
  tank/ds1/media/audiobooks:
  tank/ds1/media/movies:
  tank/ds1/media/music:
  tank/ds1/media/photos:
  tank/ds1/media/tv:
  tank/ds1/media/videos:
