---
debian_backports_additional_components:
  - contrib
docker_users:
  - joe
# Run zfsunlock automatically in initramfs to unlock root pool
dropbear_initramfs_options: '-c /usr/bin/zfsunlock'
dropbear_initramfs_ssh_authorized_keys:
  - https://github.com/joenyland.keys
postfix_inet_interfaces: all
postfix_networks:
  - "127.0.0.0/8"
  - "172.17.0.0/16"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
  - "{{ subnets.vpn.ipv4.cidr }}"
  - "{{ subnets.cloud.ipv4.cidr }}"
  - "{{ subnets.lan.ipv4.cidr }}"
postfix_relay_host:
  host: smtp.postmarkapp.com
  port: 587
  sasl_auth_enabled: true
qbittorrent_users:
  - joe
nfs_exports:
  /home:
    client_permissions:
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility
        - crossmnt # Allow mounts inside /home to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
  /tank:
    client_permissions:
      10.10.0.0/16:
        - rw # Allow read/write access
        - insecure # Allow ports >1025 (mainly for macOS compatibility)
        - crossmnt # Allow mounts inside /tank to be visible
        - no_root_squash # Do not squash root user access to the anonymous user
samba_shares:
  tank:
    path: /tank
    valid_users: joe
    read_only: false
sanoid_templates:
  bpool:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  rpool:
    autosnap: 'yes'
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 30
    monthly: 3
    yearly: 0
  none:
    autosnap: 'no'
    autoprune: 'no'
    frequently: 0
    hourly: 0
    daily: 0
    monthly: 0
    yearly: 0
sanoid_policies:
  bpool:
    use_template: bpool
    recursive: 'yes'
  rpool:
    use_template: rpool
    recursive: 'yes'
  rpool/tank/downloads:
    use_template: none
    recursive: 'yes'
off_site_backup_destination_host: backup-pi
off_site_backup_source_host: server.lan.home.joe.nyland.io
zfs_datasets:
  # Boot
  bpool:
    devices: 'off'
    acltype: posix
    xattr: sa
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /boot
  bpool/BOOT:
    canmount: 'off'
    mountpoint: none
  bpool/BOOT/debian:
    mountpoint: /boot

  # Root
  rpool:
    encryption: aes-256-gcm
    keylocation: prompt
    keyformat: passphrase
    acltype: posix
    xattr: sa
    dnodesize: auto
    compression: lz4
    normalization: formD
    relatime: 'on'
    canmount: 'off'
    mountpoint: /
  rpool/ROOT:
    canmount: 'off'
    mountpoint: 'none'
  rpool/ROOT/debian:
    canmount: noauto
    mountpoint: /
  rpool/tank:
  rpool/tank/archive:
  rpool/tank/archive/apps:
  rpool/tank/archive/certificates:
  rpool/tank/archive/drivers:
  rpool/tank/archive/firmware:
  rpool/tank/archive/gaming:
  rpool/tank/archive/manuals:
  rpool/tank/archive/os:
  rpool/tank/archive/vms:
  rpool/tank/backups:
  rpool/tank/backups/images:
  rpool/tank/downloads:
    syncoid:sync: 'false'
  rpool/tank/home:
    mountpoint: /home
  rpool/tank/home/joe:
  rpool/tank/home/root:
    mountpoint: /root
  rpool/tank/media/audiobooks:
  rpool/tank/media/movies:
  rpool/tank/media/music:
  rpool/tank/media/photos:
  rpool/tank/media/tv:
  rpool/tank/media/videos:
  rpool/var:
    canmount: 'off'
  rpool/var/lib:
    canmount: 'off'
  rpool/var/lib/docker:
    com.sun:auto-snapshot: false
  rpool/var/lib/plexmediaserver:
  rpool/var/lib/qbittorrent:
  rpool/var/log:
  rpool/var/spool:
