---
ssh_authorized_keys: [] # Authorized keys are managed by the provider (https://console.scaleway.com/project/ssh-keys)
ssh_permit_root_login: true # Log in as root by default
sudo_users: [] # root is used, so no need to setup sudo for any users
homeshick_dotfiles_repos: {} # Unable to install dotfiles on this host as it's IPv6 only and GitHub doesn't run IPv6
