---
hostname: VPS
domain: cloud.joe.nyland.io
ssh_authorized_keys: [] # Authorized keys are managed by the provider (https://console.scaleway.com/project/ssh-keys)
ssh_permit_root_login: true # Log in as root by default
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe@server.home.joe.nyland.io
  joe: root
  syncoid: joe
wireguard_interfaces:
  wg0:
    address: fdff:0205:2005::22/123, 172.16.255.34/27
    listen_port: 51820
    mtu: 1412
    post_up:
      - wg set %i private-key /etc/wireguard/private.key
    dns:
      - fdff:205:2005::21
      - 172.16.255.33
      - cloud.joe.nyland.io
    peers:
      - name: Router
        public_key: P3lmTwJlnV/K5CLPkK77C5qOWapCimop5c8eox3FSFg=
        allowed_ips:
          - fdff:205:2005::/123
          - fdff:205:2005::20/123
          - fdaa:205:2005:10::/64
          - fdaa:1610:2007:200::/64
          - 172.16.255.0/27
          - 172.16.255.32/27
          - 10.10.0.0/16
          - 192.168.200.0/24
        endpoint: home.joe.nyland.io:51821
nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/nyland.io.conf
    backup: false
    config:
      servers:
        - core:
            listen:
              - address: '[::]'
                port: 80
            ipv6only: true
            server_name: nyland.io
          locations:
            - location: ~ ^/~(.+?)(/.*)?$
              core:
                alias: /home/$1/public_html$2
              autoindex:
                enable: true
