---
ssh_authorized_keys: [] # Authorized keys are managed by the provider (https://console.scaleway.com/project/ssh-keys)
ssh_permit_root_login: true # Log in as root by default
postfix_aliases:
  mailer-daemon: postmaster
  postmaster: root
  nobody: root
  hostmaster: root
  usenet: root
  news: root
  webmaster: root
  www: root
  ftp: root
  abuse: root
  noc: root
  security: root
  root: joe@server.home.joe.nyland.io
  joe: root
  syncoid: joe
wireguard_interfaces:
  wg0:
    address: 10.8.1.3/24, fc00:f00d:cafe:8:1::3/80
    mtu: 1400
    post_up:
      - wg set %i private-key /etc/wireguard/private.key
    dns:
      - fc00:f00d:cafe:8:1::1
      - 10.8.1.1
      - cloud.joe.nyland.io
    peers:
      - name: Router
        public_key: P3lmTwJlnV/K5CLPkK77C5qOWapCimop5c8eox3FSFg=
        allowed_ips: 10.8.1.0/24, 10.10.0.0/16, fc00:f00d:cafe:8:1::/80, fc00:f00d:cafe:10::/64
        endpoint: home.joe.nyland.io:51821
        keep_alive: 25
nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/nyland.io.conf
    backup: false
    config:
      servers:
        - core:
            listen:
              - address: '[::]'
                port: 80
            ipv6only: true
            server_name: nyland.io
          locations:
            - location: ~ ^/~(.+?)(/.*)?$
              core:
                alias: /home/$1/public_html$2
              autoindex:
                enable: true
