---
- name: Setup all systems
  hosts: all
  vars:
    ssh_authorized_keys:
      - user: joe
        key: https://github.com/joenyland.keys
    sudo_users:
      - joe
  roles:
    - role: updates
      become: true
    - role: sudo
      become: true
    - role: ssh
      become: true
    - role: vim
      become: true
    - role: utils
      become: true
    - role: debian-backports
      become: true
    - homeshick

- name: Setup Server
  hosts: server
  vars:
    backup_sources:
      - /
      - /boot
      - /boot/efi
    backup_destination: /tank/archive/backups/files/{{ansible_hostname}}/{{ansible_hostname}}.tar.gz
    postfix_mail_name: server.home.joe.nyland.io
    postfix_host_name: server.home.joe.nyland.io
    postfix_destinations:
      - localhost
      - server
      - server.home.joe.nyland.io
      - home.joe.nyland.io
    postfix_networks:
      - "127.0.0.0/8"
      - "[::ffff:127.0.0.0]/104"
      - "[::1]/128"
    postfix_relay_host:
      host: smtp.postmarkapp.com
      port: 587
    postfix_aliases:
      root: joe
    postfix_inet_interfaces: all
    qbittorrent_users:
      - joe
  roles:
    - role: backup
      become: true
    - role: postfix
      become: true
    - role: plexmediaserver
      become: true
    - role: samba
      become: true
    - role: qbittorrent
      become: true
    - role: abcde
      become: true
