---
- name: Setup
  hosts: all
  become: true

  tasks:
    # TODO: dotfiles
    # TODO: Set my UID to 501
    # TODO: Wireguard
    # TODO: Transmission
    # TODO: Plex
    # TODO: NFS server
    # TODO: Disable root SSH
    # TODO: Disable SSH with password

    - name: Configure user
      user:
        name: joe

    - name: Add my SSH keys
      authorized_key:
        user: joe
        key: https://github.com/joenyland.keys
        exclusive: true  # Only allow keys specified here

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade system packages
      apt:
        upgrade: true
        autoremove: true  # Remove old packages
        purge: true  # Purge config files for old packages that were removed

    - name: Install utils
      apt:
        name:
          - htop
          - multitail
          - vim
          - git

    - name: Set default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: Allow users in the sudo group to use sudo without providing their password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- name: Install Unifi controller
  hosts: all
  become: true

  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg

    - name: Add MongoDB apt GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.6.asc

    - name: Add MongoDB repository
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main
        filename: mongodb

    - name: Add AdoptOpenJDK apt GPG key
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

    - name: Add AdoptOpenJDK repository
      apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main
        filename: adoptopenjdk

    - name: Add Unifi apt GPG key
      apt_key:
        url: https://dl.ui.com/unifi/unifi-repo.gpg

    - name: Add Unifi repository
      apt_repository:
        repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
        filename: unifi

    - name: Install Java
      apt:
        name: adoptopenjdk-8-hotspot-jre
        update_cache: true
        cache_valid_time: 86400

    - name: Install Unifi controller
      apt:
        name: unifi
        update_cache: true
        cache_valid_time: 86400

    - name: Set JAVA_HOME in init script for Unifi controller
      lineinfile:
        path: /etc/init.d/unifi
        regexp: 'JAVA_HOME=\/usr\/lib\/jvm\/'
        line: 'JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-jre-amd64'

    - name: Ensure Unifi controller is started and enabled to start on boot
      service:
        name: unifi
        state: started
        enabled: true

- name: Setup scheduled tasks
  hosts: all

  tasks:
    - name: Back up /srv every night
      cron:
        name: Back up /srv every night
        hour: 2
        minute: 0
        job: >-
          rsync -avPh /srv/ /mnt/backup/
          --exclude lost+found
          --exclude '.*'
          --include 'Downloads/'
          --include 'Downloads/In Progress/'
          --exclude 'Downloads/***'
          --delete
          --quiet
