---
- name: Setup Server
  hosts: server
  become: true

  vars:
    postfix_mail_name: server.home.joe.nyland.io
    postfix_host_name: server.home.joe.nyland.io
    postfix_destinations:
      - localhost
      - server
      - server.home.joe.nyland.io
      - home.joe.nyland.io
    postfix_networks:
      - "127.0.0.0/8"
      - "[::ffff:127.0.0.0]/104"
      - "[::1]/128"
    postfix_relay_host:
      host: smtp.postmarkapp.com
      port: 587
    postfix_aliases:
      root: joe
    postfix_inet_interfaces: all
    qbittorrent_groups:
      - users
    ssh_authorized_keys:
      - user: joe
        key: https://github.com/joenyland.keys
    sudo_users:
      - joe

  roles:
    - updates
    - sudo
    - ssh
    - vim
    - utils
    - homeshick
    - debian-backports
    - postfix
    - plexmediaserver
    - samba
    - qbittorrent
    - abcde
