---
- name: Setup
  hosts: server
  become: true

  tasks:
    - name: Configure user
      user:
        name: joe
        groups:
          - sudo
        append: true

    - name: Add my SSH keys
      authorized_key:
        user: joe
        key: https://github.com/joenyland.keys
        exclusive: true  # Only allow keys specified here

    - name: Configure sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo '
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade system packages
      apt:
        upgrade: true
        autoremove: true  # Remove old packages
        purge: true  # Purge config files for old packages that were removed

    - name: Install utils
      apt:
        name:
          - htop
          - multitail
          - vim
          - git
          - tree
          - screen
          - gnupg
          - rsync
          - bash-completion

    - name: Set default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: Allow users in the sudo group to use sudo without providing their password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PermitRootLogin
        line: PermitRootLogin no
        validate: /usr/sbin/sshd -t -f %s

    - name: Disable password-based login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PasswordAuthentication
        line: PasswordAuthentication no
        validate: /usr/sbin/sshd -t -f %s

    - name: Install homeshick
      become: false
      git:
        repo: https://github.com/andsens/homeshick.git
        dest: /home/joe/.homesick/repos/homeshick
        force: yes

    - name: Ensure /srv has the correct permissions
      file:
        path: /srv
        state: directory
        owner: joe
        group: users
        mode: 0755

    - name: Configure IPv6 privacy extensions
      sysctl:
        name: net.ipv6.conf.enp2s0.use_tempaddr
        value: '2'
        sysctl_file: /etc/sysctl.d/90-ipv6-privacy-ext.conf

- name: Setup transmission-daemon
  hosts: server
  become: true
  vars:
    transmission_download_directory: /srv/Downloads
    transmission_in_progress_download_directory: /srv/Downloads/In Progress
    transmission_rpc_whitelist: 127.0.0.1,::1,192.168.10.*,192.168.8.*
  tasks:
    - name: Create /srv/Downloads
      file:
        path: /srv/Downloads
        state: directory
        owner: joe
        group: users
        mode: '2775'

    - name: Create /srv/Downloads/In Progress
      file:
        path: /srv/Downloads/In Progress
        state: directory
        owner: joe
        group: users
        mode: '2775'

    - name: Install transmission-daemon
      apt:
        name: transmission-daemon

    - name: Ensure transmission-daemon is started and configured to start automatically
      service:
        name: transmission-daemon
        state: started
        enabled: true

    - name: Add transmission-daemon user to the users group
      user:
        name: debian-transmission
        groups:
          - users
        append: true

    - name: Configure transmission-daemon
      template:
        dest: /etc/transmission-daemon/settings.json
        src: ../templates/transmission-daemon/settings.json.j2
        owner: debian-transmission
        group: debian-transmission
        mode: '0600'
      register: transmission_config

    - name: Apply config changes
      service:
        name: transmission-daemon
        state: reloaded
      when: transmission_config.changed

- name: Setup Plex Media server
  hosts: server
  become: true

  tasks:
    - name: Install packages
      apt:
        name: apt-transport-https

    - name: Install GPG key
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present
        keyring: /etc/apt/trusted.gpg.d/plex.gpg

    - name: Install repo
      apt_repository:
        repo: 'deb https://downloads.plex.tv/repo/deb/ public main'
        state: present
        filename: plex

    - name: Install Plex Media Server
      apt:
        name: plexmediaserver
        update_cache: true
        cache_valid_time: 86400

    - name: Ensure plexmediaserver is started and configured to start automatically
      service:
        name: plexmediaserver
        state: started
        enabled: true

- name: Setup WireGuard
  hosts: server
  become: true

  tasks:
    - name: Install WireGuard
      apt:
        name: wireguard

    - name: Configure WireGuard
      template:
        dest: /etc/wireguard/wg0.conf
        src: ../templates/wireguard/wg0.conf.j2
        mode: '0600'
      register: wireguard_config

    - name: Ensure WireGuard is started and configured to start automatically
      service:
        name: wg-quick@wg0
        state: started
        enabled: true

    - name: Apply WireGuard config changes
      service:
        name: wg-quick@wg0
        state: restarted
      when: wireguard_config.changed

    - name: Configure IPv4 routing
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.d/90-ipv4-routing.conf

- name: Setup Sambda file server
  hosts: server
  become: true

  tasks:
    - name: Install Samba
      apt:
        name: samba

    - name: Configure Samba
      template:
        dest: /etc/samba/smb.conf
        src: ../templates/samba/smb.conf.j2
      register: samba_config

    - name: Ensure Samba is started and configured to start automatically
      service:
        name: smbd
        state: started
        enabled: true

    - name: Apply Samba config changes
      service:
        name: smbd
        state: restarted
