---
- name: Setup
  hosts: server
  become: true

  tasks:
    - name: Configure user
      user:
        name: joe
        groups:
          - sudo
        append: true

    - name: Add my SSH keys
      authorized_key:
        user: joe
        key: https://github.com/joenyland.keys
        exclusive: true  # Only allow keys specified here

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade system packages
      apt:
        upgrade: true
        autoremove: true  # Remove old packages
        purge: true  # Purge config files for old packages that were removed

    - name: Install utils
      apt:
        name:
          - htop
          - multitail
          - vim
          - git
          - tree
          - screen
          - gnupg
          - rsync
          - bash-completion

    - name: Set default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: Allow users in the sudo group to use sudo without providing their password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo '
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PermitRootLogin
        line: PermitRootLogin no
        validate: /usr/sbin/sshd -t -f %s

    - name: Disable password-based login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PasswordAuthentication
        line: PasswordAuthentication no
        validate: /usr/sbin/sshd -t -f %s

    - name: Install homeshick
      git:  # noqa git-latest
        repo: https://github.com/andsens/homeshick.git
        dest: /home/joe/.homesick/repos/homeshick
        force: true

    - name: Ensure /srv has the correct permissions
      file:
        path: /srv
        state: directory
        owner: joe
        group: users
        mode: 0755

- name: Setup Plex Media server
  hosts: server
  become: true

  tasks:
    - name: Install packages
      apt:
        name: apt-transport-https

    - name: Install GPG key
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present
        keyring: /etc/apt/trusted.gpg.d/plex.gpg

    - name: Install repo
      apt_repository:
        repo: 'deb https://downloads.plex.tv/repo/deb/ public main'
        state: present
        filename: plex
      register: plex_repo

    - name: Update package cache  # noqa no-handler
      apt:
        update_cache: true
        cache_valid_time: 86400
      when: plex_repo.changed

    - name: Install Plex Media Server
      apt:
        name: plexmediaserver

    # The Plex installation disables the repo, so we re-enable it here
    - name: Re-enable repo
      apt_repository:
        repo: 'deb https://downloads.plex.tv/repo/deb/ public main'
        state: present
        filename: plex

    - name: Configure plexmediaserver service
      service:
        name: plexmediaserver
        state: started
        enabled: true

- name: Install Docker
  hosts: server
  become: true

  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker apt GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: true
        cache_valid_time: 86400

    - name: Install Docker Compose
      apt:
        name: docker-compose-plugin
        update_cache: true
        cache_valid_time: 86400

    - name: Enable Docker service
      service:
        name: docker
        enabled: true

    - name: Adding user 'joe' to group 'docker'
      user:
        name: joe
        groups: docker
        append: true

- name: Setup Sambda file server
  hosts: server
  become: true

  tasks:
    - name: Install Samba
      apt:
        name: samba

    - name: Configure Samba
      copy:
        dest: /etc/samba/smb.conf
        src: samba/smb.conf
        mode: '640'
      notify: restart_samba

    - name: Configure Samba service
      service:
        name: smbd
        state: started
        enabled: true
      register: samba_service

  handlers:
    - name: restart_samba
      service:
        name: smbd
        state: restarted
      when: samba_service.enabled

- name: Setup qBittorrent
  hosts: server
  become: true

  tasks:
    - name: Create qbittorrent system user
      user:
        name: qbittorrent
        system: true
        shell: /usr/sbin/nologin
        create_home: false

    - name: Add the qbittorrent user to the users group
      user:
        name: qbittorrent
        groups:
          - users
        append: true

    - name: Install qbittorrent-nox
      apt:
        name: qbittorrent-nox

    - name: Create systemd service for qBittorrent
      copy:
        dest: /etc/systemd/system/qbittorrent.service
        src: qbittorrent/qbittorrent.service
        mode: '644'
      notify: reload_systemd

    - name: Create qbittorrent config directory
      file:
        name: /var/lib/qbittorrent/.config/qBittorrent/
        state: directory
        owner: qbittorrent
        group: qbittorrent
        mode: '755'

    - name: Configure qBittorrent
      copy:
        dest: /var/lib/qbittorrent/.config/qBittorrent/qBittorrent.conf
        src: qbittorrent/qbittorrent.conf
        owner: qbittorrent
        group: qbittorrent
        force: false
        mode: '644'
      notify: restart_qbittorrent

    - name: Configure qbittorrent service
      service:
        name: qbittorrent
        state: started
        enabled: true
      register: qbittorrent_service

    - name: Create /srv/Downloads
      file:
        path: /srv/Downloads
        state: directory
        owner: joe
        group: users
        mode: '2775'

  handlers:
    - name: restart_qbittorrent
      service:
        name: qbittorrent
        state: restarted
      when: qbittorrent_service.enabled

    - name: reload_systemd
      systemd:
        daemon_reload: true

- name: Setup abcde
  hosts: server
  become: true
  tasks:
    - name: Install abcde
      apt:
        name: abcde
    - name: Configure abcde
      copy:
        dest: /etc/abcde.conf
        src: abcde/abcde.conf
