---
- name: Configure crons to perform off-site backups
  cron:
    user: "{{ off_site_backup_user }}"
    name: Off-site backup {{ item.source }} -> {{ item.destination }}
    job: >
      [ $(pgrep syncoid) ] || /usr/sbin/syncoid
      --no-privilege-elevation
      --recursive
      --no-sync-snap
      {{ item.source }}
      {{ item.destination }}
    special_time: daily
  loop: "{{ off_site_backup_tasks }}"
  loop_control:
    label: "{{ item.source }} -> {{ item.destination }}"
