---
- name: Install cron
  apt:
    name: cron
    update_cache: true

- name: Configure crons to perform off-site backups
  cron:
    user: "{{ off_site_backup_user }}"
    name: Off-site backup {{ item.source }} -> {{ item.destination }}
    job: >
      [ $(pgrep syncoid) ] || /usr/sbin/syncoid
      --no-privilege-elevation
      --recursive
      --no-sync-snap
      --quiet
      {% if item.send_options is defined %}
      --sendoptions="{{ item.send_options | join }}"
      {% endif %}
      {{ item.source }}
      {{ item.destination }}
    minute: "{{ item.minute | default('0') }}"
    hour: "{{ item.hour | default('0') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
  loop: "{{ off_site_backup_tasks }}"
  loop_control:
    label: "{{ item.source }} -> {{ item.destination }}"
