---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
      - name: ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: "./"
          override-deps: rich>=9.5.1,<11.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: sudo pip install -r requirements.txt
      - name: Test with Molecule
        run: sudo molecule test -s ci
