---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./"

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
